Imports System.Globalization
Imports MySql.Data.MySqlClient

Public Class frmPOS

    Private foundStudentId As Integer = 0
    Private activeCategory As String = ""

    ' Column names of the top grid (dgvlistproducts) as generated by the designer
    Private Const COL_NAME As String = "DataGridViewTextBoxColumn1"
    Private Const COL_SIZE As String = "DataGridViewTextBoxColumn2"
    Private Const COL_PRICE As String = "DataGridViewTextBoxColumn3"
    Private Const COL_STOCK As String = "DataGridViewTextBoxColumn4"

    Private ReadOnly gradeLevels As String() = {"Kinder", "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6",
        "Grade 7", "Grade 8", "Grade 9", "Grade 10", "Grade 11", "Grade 12",
        "1st Year College", "2nd Year College", "3rd Year College", "4th Year College"}

    ' ================= LOAD =================
    Private Sub frmPOS_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        TextBox4.Text = currentuser.FullName
        TextBox4.ReadOnly = True

        lblname.Text = currentuser.FullName
        lblposition.Text = currentuser.Role
        lbldatetime.Text = "Today is " & DateTime.Now.ToString("dddd, MMMM d, yyyy")

        ComboBox6.DropDownStyle = ComboBoxStyle.DropDownList   ' Grade Level
        ComboBox4.DropDownStyle = ComboBoxStyle.DropDownList   ' Payment Method

        TextBox1.ReadOnly = True   ' Total Amount
        TextBox3.ReadOnly = True   ' Program / Strand
        TextBox7.ReadOnly = True   ' Reference No.
        TextBox8.ReadOnly = True   ' Amount Received
        TextBox9.ReadOnly = True   ' Amount Change

        SetupGrid(dgvlistproducts)
        SetupGrid(DataGridView1)
        dgvlistproducts.Columns(COL_PRICE).DefaultCellStyle.Format = "N2"
        DataGridView1.Columns("UnitPrice").DefaultCellStyle.Format = "N2"
        DataGridView1.Columns("SubTotal").DefaultCellStyle.Format = "N2"

        ' Quantity can never go below 0 (no negatives)
        NumericUpDown1.DecimalPlaces = 0
        NumericUpDown1.Minimum = 0
        ResetQuantity()

        ComboBox6.Items.Clear()
        ComboBox6.Items.AddRange(gradeLevels)

        ComboBox4.Items.Clear()
        ComboBox4.Items.AddRange(New String() {"Cash", "Salary Deduction"})
        ComboBox4.Enabled = False   ' filled in by frmPayment

        DateTimePicker1.Value = DateTime.Today
        TextBox1.Text = "0.00"
        ResetCustomerInfo()
    End Sub

    Private Sub SetupGrid(dgv As DataGridView)
        dgv.ReadOnly = True
        dgv.AllowUserToAddRows = False
        dgv.AllowUserToDeleteRows = False
        dgv.MultiSelect = False
        dgv.SelectionMode = DataGridViewSelectionMode.FullRowSelect
    End Sub

    ' ================= STUDENT LOOKUP =================
    Private Sub PictureBox1_Click(sender As Object, e As EventArgs) Handles PictureBox1.Click
        LookupStudent()
    End Sub

    Private Sub txtSearch_KeyDown(sender As Object, e As KeyEventArgs) Handles txtSearch.KeyDown
        If e.KeyCode = Keys.Enter Then
            LookupStudent()
            e.SuppressKeyPress = True
        End If
    End Sub

    Private Sub LookupStudent()
        If String.IsNullOrWhiteSpace(txtSearch.Text) Then Exit Sub

        Dim dt As DataTable = GetDataTable("SELECT student_id, first_name, last_name, grade_level, section FROM TBL_STUDENTS WHERE student_no = @n",
                                            New String() {"@n"}, New Object() {txtSearch.Text.Trim()})

        If dt.Rows.Count > 0 Then
            Dim r As DataRow = dt.Rows(0)
            foundStudentId = Convert.ToInt32(r("student_id"))
            TextBox2.Text = r("first_name").ToString() & " " & r("last_name").ToString()

            Dim grade As String = r("grade_level").ToString()
            If Not ComboBox6.Items.Contains(grade) Then ComboBox6.Items.Add(grade)
            ComboBox6.Text = grade
            TextBox3.Text = If(IsDBNull(r("section")), "", r("section").ToString())

            TextBox2.ReadOnly = True
        Else
            foundStudentId = 0
            TextBox2.Clear()
            ComboBox6.SelectedIndex = -1
            TextBox3.Clear()

            TextBox2.ReadOnly = False
            MsgBox("Student number not found. You can type the buyer's name manually for a walk-in / employee sale.", vbInformation, "Point of Sale")
            TextBox2.Focus()
        End If
    End Sub

    ' ================= CATEGORY BUTTONS + PRODUCT SEARCH =================
    Private Sub CategoryButton_Click(sender As Object, e As EventArgs) Handles Button1.Click, Button2.Click, Button3.Click, Button4.Click, Button5.Click, Button6.Click
        Dim btn As Button = DirectCast(sender, Button)
        ' Button4 says "Other Items" but the category in the database is "Other Bookstore Items"
        activeCategory = If(btn Is Button4, "Other Bookstore Items", btn.Text)
        ResetQuantity()
        LoadProducts()
    End Sub

    Private Sub TextBox5_TextChanged(sender As Object, e As EventArgs) Handles TextBox5.TextChanged
        ResetQuantity()
        LoadProducts()
    End Sub

    Private Sub PictureBox2_Click(sender As Object, e As EventArgs) Handles PictureBox2.Click
        LoadProducts()
    End Sub

    Private Sub LoadProducts()
        dgvlistproducts.Rows.Clear()

        Dim keyword As String = TextBox5.Text.Trim()
        If activeCategory = "" AndAlso keyword = "" Then Exit Sub   ' nothing chosen yet -> blank list

        Dim query As String =
            "SELECT v.variant_id, v.product_code, p.product_name, p.product_description, c.category_name, ct.type_name, " &
            "v.size, p.unit_price, v.quantity_on_hand, v.reorder_level " &
            "FROM TBL_PRODUCT_VARIANTS v " &
            "INNER JOIN TBL_PRODUCTS p ON v.product_id = p.product_id " &
            "INNER JOIN TBL_CATEGORY_TYPES ct ON p.category_type_id = ct.category_type_id " &
            "INNER JOIN TBL_CATEGORIES c ON ct.category_id = c.category_id " &
            "WHERE p.status = 'Active' AND (@cat = '' OR c.category_name = @cat) " &
            "AND (@kw = '' OR v.product_code LIKE @like OR p.product_name LIKE @like) " &
            "ORDER BY p.product_name, v.size"

        Dim dt As DataTable = GetDataTable(query,
            New String() {"@cat", "@kw", "@like"},
            New Object() {activeCategory, keyword, "%" & keyword & "%"})

        For Each r As DataRow In dt.Rows
            Dim stock As Integer = Convert.ToInt32(r("quantity_on_hand"))
            Dim reorder As Integer = Convert.ToInt32(r("reorder_level"))
            Dim status As String = If(stock <= 0, "Out of Stock", If(stock <= reorder, "Low Stock", "In Stock"))

            Dim idx As Integer = dgvlistproducts.Rows.Add(
                r("product_code").ToString(),
                r("product_name").ToString(),
                If(IsDBNull(r("product_description")), "", r("product_description").ToString()),
                r("category_name").ToString(),
                r("type_name").ToString(),
                r("size").ToString(),
                Convert.ToDecimal(r("unit_price")),
                stock,
                reorder,
                status)
            dgvlistproducts.Rows(idx).Tag = Convert.ToInt32(r("variant_id"))
        Next

        ClearGridSelection(dgvlistproducts)
    End Sub

    ' Clicking an item sets the quantity to 1 (user can raise it, never above stock)
    Private Sub dgvlistproducts_CellClick(sender As Object, e As DataGridViewCellEventArgs) Handles dgvlistproducts.CellClick
        If e.RowIndex < 0 Then Exit Sub

        Dim stock As Integer = Convert.ToInt32(dgvlistproducts.Rows(e.RowIndex).Cells(COL_STOCK).Value)
        If stock <= 0 Then
            ResetQuantity()
            MsgBox("This item is out of stock.", vbExclamation, "Point of Sale")
            Exit Sub
        End If

        NumericUpDown1.Maximum = stock
        NumericUpDown1.Value = 1
    End Sub

    ' ================= QUANTITY: NO NEGATIVES =================
    Private Sub NumericUpDown1_KeyPress(sender As Object, e As KeyPressEventArgs) Handles NumericUpDown1.KeyPress
        ' digits only: blocks "-", "." and letters
        If Not Char.IsDigit(e.KeyChar) AndAlso Not Char.IsControl(e.KeyChar) Then e.Handled = True
    End Sub

    Private Sub ResetQuantity()
        NumericUpDown1.Value = 0
        NumericUpDown1.Maximum = 0
    End Sub

    ' ================= ADD TO CART =================
    Private Sub btnAddToCart_Click(sender As Object, e As EventArgs) Handles btnAddToCart.Click
        If dgvlistproducts.SelectedRows.Count = 0 Then
            MsgBox("Please click an item in the list first.", vbExclamation, "Point of Sale")
            Exit Sub
        End If

        Dim qty As Integer = Convert.ToInt32(NumericUpDown1.Value)   ' value is validated/clamped (>= 0)
        If qty <= 0 Then
            MsgBox("Quantity must be at least 1.", vbExclamation, "Point of Sale")
            Exit Sub
        End If

        Dim prow As DataGridViewRow = dgvlistproducts.SelectedRows(0)
        Dim variantId As Integer = Convert.ToInt32(prow.Tag)
        Dim stock As Integer = Convert.ToInt32(prow.Cells(COL_STOCK).Value)
        Dim price As Decimal = Convert.ToDecimal(prow.Cells(COL_PRICE).Value)

        ' Is this item already in the cart? Then add to its quantity
        Dim existing As DataGridViewRow = Nothing
        For Each crow As DataGridViewRow In DataGridView1.Rows
            If Convert.ToInt32(crow.Tag) = variantId Then
                existing = crow
                Exit For
            End If
        Next

        Dim alreadyInCart As Integer = If(existing IsNot Nothing, Convert.ToInt32(existing.Cells("Quantity").Value), 0)
        If alreadyInCart + qty > stock Then
            MsgBox("Only " & stock & " item(s) in stock. You already have " & alreadyInCart & " in the cart.", vbExclamation, "Point of Sale")
            Exit Sub
        End If

        If existing IsNot Nothing Then
            Dim newQty As Integer = alreadyInCart + qty
            existing.Cells("Quantity").Value = newQty
            existing.Cells("SubTotal").Value = newQty * price
        Else
            Dim idx As Integer = DataGridView1.Rows.Add(
                prow.Cells(COL_NAME).Value,
                prow.Cells(COL_SIZE).Value,
                qty,
                price,
                qty * price)
            DataGridView1.Rows(idx).Tag = variantId
        End If

        ResetQuantity()
        ClearGridSelection(dgvlistproducts)
        ClearGridSelection(DataGridView1)
        RecalculateTotal()
        InvalidatePayment()
    End Sub

    ' ================= REMOVE ITEM =================
    Private Sub btnRemoveItem_Click(sender As Object, e As EventArgs) Handles btnRemoveItem.Click
        If DataGridView1.Rows.Count = 0 Then
            MsgBox("The cart is already empty.", vbInformation, "Point of Sale")
            Exit Sub
        End If

        If DataGridView1.SelectedRows.Count > 0 Then
            ' an item was clicked -> remove that item only
            DataGridView1.Rows.RemoveAt(DataGridView1.SelectedRows(0).Index)
        Else
            ' nothing clicked -> remove everything
            If MsgBox("No item is selected. Remove ALL items from the cart?", vbYesNo + vbQuestion, "Point of Sale") <> MsgBoxResult.Yes Then Exit Sub
            DataGridView1.Rows.Clear()
        End If

        ClearGridSelection(DataGridView1)
        RecalculateTotal()
        InvalidatePayment()
    End Sub

    ' Clicking the empty grey area of the cart un-selects, so "Remove Item" removes all again
    Private Sub DataGridView1_MouseDown(sender As Object, e As MouseEventArgs) Handles DataGridView1.MouseDown
        If DataGridView1.HitTest(e.X, e.Y).Type = DataGridViewHitTestType.None Then
            ClearGridSelection(DataGridView1)
        End If
    End Sub

    ' ================= CLEAR (customer + payment method only) =================
    Private Sub btnClear_Click(sender As Object, e As EventArgs) Handles btnClear.Click
        ResetCustomerInfo()          ' Student No., Grade Level (+ Student Name and Program/Strand, since they auto-fill from Student No.)
        ComboBox4.SelectedIndex = -1 ' Payment Method
    End Sub

    ' ================= CANCEL TRANSACTION =================
    Private Sub btnCancelTransaction_Click(sender As Object, e As EventArgs) Handles btnCancelTransaction.Click
        If MsgBox("Cancel this transaction? All entered details and both item lists will be cleared.", vbYesNo + vbQuestion, "Point of Sale") = MsgBoxResult.Yes Then
            ResetAll()
        End If
    End Sub

    ' ================= SETTLE PAYMENT (opens frmPayment) =================
    Private Sub btnSettlePayment_Click(sender As Object, e As EventArgs) Handles btnSettlePayment.Click
        If DataGridView1.Rows.Count = 0 Then
            MsgBox("Add at least one item to the cart first.", vbExclamation, "Point of Sale")
            Exit Sub
        End If

        Dim grandTotal As Decimal = ToMoney(TextBox1.Text)

        Using frm As New frmPayment()
            frm.GrandTotal = grandTotal                     ' frmPOS -> frmPayment
            If frm.ShowDialog(Me) = DialogResult.OK Then    ' frmPayment -> frmPOS
                TextBox7.Text = frm.ResultORNo
                DateTimePicker1.Value = frm.ResultDate
                ComboBox4.Text = frm.ResultMethod
                TextBox8.Text = frm.ResultReceived.ToString("N2")
                TextBox9.Text = frm.ResultChange.ToString("N2")
            End If
        End Using
    End Sub

    ' ================= SAVE TRANSACTION =================
    Private Sub btnSaveTransaction_Click(sender As Object, e As EventArgs) Handles btnSaveTransaction.Click
        If DataGridView1.Rows.Count = 0 Then
            MsgBox("Add at least one item to the cart first.", vbExclamation, "Point of Sale")
            Exit Sub
        End If

        If String.IsNullOrWhiteSpace(TextBox7.Text) OrElse ComboBox4.SelectedIndex = -1 Then
            MsgBox("Payment is not settled (or the payment method was cleared). Click 'Settle Payment' first.", vbExclamation, "Point of Sale")
            Exit Sub
        End If

        If String.IsNullOrWhiteSpace(TextBox2.Text) Then
            MsgBox("Enter the buyer's name (or look up a Student No.).", vbExclamation, "Point of Sale")
            Exit Sub
        End If

        Dim total As Decimal = ToMoney(TextBox1.Text)
        Dim received As Decimal = ToMoney(TextBox8.Text)
        Dim change As Decimal = ToMoney(TextBox9.Text)
        If total <= 0 OrElse received < total OrElse change < 0 Then
            MsgBox("The payment does not cover the total. Click 'Settle Payment' again.", vbExclamation, "Point of Sale")
            Exit Sub
        End If

        Dim buyerType As String = If(foundStudentId > 0, "Student", "Walk-in")
        Dim saved As Boolean = False

        Try
            If Not connection() Then Exit Sub
            Dim trans As MySqlTransaction = cn.BeginTransaction()
            Try
                Dim transactionId As Long = 0
                Dim insTxn As String = "INSERT INTO TBL_TRANSACTIONS " &
                    "(transaction_no, buyer_type, student_id, buyer_name, or_no, or_date, payment_method, total_amount, amount_paid, amount_change, created_by, status) " &
                    "VALUES (@tno, @bt, @sid, @bn, @orno, @ord, @pm, @tot, @paid, @chg, @by, 'Completed')"

                Using c1 As New MySqlCommand(insTxn, cn, trans)
                    c1.Parameters.AddWithValue("@tno", NewTransactionNo())
                    c1.Parameters.AddWithValue("@bt", buyerType)
                    c1.Parameters.AddWithValue("@sid", If(foundStudentId > 0, CType(foundStudentId, Object), DBNull.Value))
                    c1.Parameters.AddWithValue("@bn", TextBox2.Text.Trim())
                    c1.Parameters.AddWithValue("@orno", TextBox7.Text.Trim())
                    c1.Parameters.AddWithValue("@ord", DateTimePicker1.Value.Date)
                    c1.Parameters.AddWithValue("@pm", ComboBox4.Text)
                    c1.Parameters.AddWithValue("@tot", total)
                    c1.Parameters.AddWithValue("@paid", received)
                    c1.Parameters.AddWithValue("@chg", change)
                    c1.Parameters.AddWithValue("@by", currentuser.UserID)
                    c1.ExecuteNonQuery()
                    transactionId = c1.LastInsertedId
                End Using

                For Each row As DataGridViewRow In DataGridView1.Rows
                    Dim variantId As Integer = Convert.ToInt32(row.Tag)
                    Dim subtotal As Decimal = Convert.ToDecimal(row.Cells("SubTotal").Value)
                    Dim qty As Integer = Convert.ToInt32(row.Cells("Quantity").Value)

                    Using c2 As New MySqlCommand("INSERT INTO TBL_TRANSACTION_ITEMS (transaction_id, variant_id, quantity, subtotal) VALUES (@t, @v, @q, @s)", cn, trans)
                        c2.Parameters.AddWithValue("@t", transactionId)
                        c2.Parameters.AddWithValue("@v", variantId)
                        c2.Parameters.AddWithValue("@q", qty)
                        c2.Parameters.AddWithValue("@s", subtotal)
                        c2.ExecuteNonQuery()
                    End Using

                    Using c3 As New MySqlCommand("UPDATE TBL_PRODUCT_VARIANTS SET quantity_on_hand = quantity_on_hand - @q WHERE variant_id = @v AND quantity_on_hand >= @q", cn, trans)
                        c3.Parameters.AddWithValue("@q", qty)
                        c3.Parameters.AddWithValue("@v", variantId)
                        If c3.ExecuteNonQuery() = 0 Then
                            Throw New Exception("Not enough stock left for " & row.Cells("ProductName").Value.ToString() & ".")
                        End If
                    End Using
                Next

                trans.Commit()
                saved = True
            Catch exInner As Exception
                trans.Rollback()
                MsgBox("Transaction failed and was rolled back: " & exInner.Message, vbCritical, "Point of Sale")
            End Try
            cn.Close()
        Catch ex As Exception
            If cn.State = ConnectionState.Open Then cn.Close()
            MsgBox("Database error: " & ex.Message, vbCritical, "Error")
        End Try

        If saved Then
            MsgBox("Transaction saved successfully. You can view it in Transaction History.", vbInformation, "Point of Sale")
            ResetAll()
        End If
    End Sub

    ' ================= HELPERS =================
    Private Sub RecalculateTotal()
        Dim total As Decimal = 0
        For Each row As DataGridViewRow In DataGridView1.Rows
            total += ToMoney(Convert.ToString(row.Cells("SubTotal").Value))
        Next
        TextBox1.Text = total.ToString("N2")
    End Sub

    Private Function ToMoney(s As String) As Decimal
        Dim v As Decimal
        If Decimal.TryParse(s, NumberStyles.Number, CultureInfo.CurrentCulture, v) Then Return v
        Return 0
    End Function

    Private Sub ClearGridSelection(dgv As DataGridView)
        dgv.ClearSelection()
        dgv.CurrentCell = Nothing
    End Sub

    ' If the cart changes after payment was settled, the old payment no longer matches the total
    Private Sub InvalidatePayment()
        If String.IsNullOrWhiteSpace(TextBox7.Text) Then Exit Sub
        ResetPaymentInfo()
        MsgBox("The cart was changed, so the payment was cleared. Click 'Settle Payment' again.", vbInformation, "Point of Sale")
    End Sub

    Private Sub ResetCustomerInfo()
        txtSearch.Clear()
        TextBox2.Clear()
        TextBox2.ReadOnly = False
        ComboBox6.SelectedIndex = -1
        TextBox3.Clear()
        foundStudentId = 0
    End Sub

    Private Sub ResetPaymentInfo()
        TextBox7.Clear()
        TextBox8.Clear()
        TextBox9.Clear()
        ComboBox4.SelectedIndex = -1
        DateTimePicker1.Value = DateTime.Today
    End Sub

    Private Sub ResetAll()
        ResetCustomerInfo()
        ResetPaymentInfo()
        activeCategory = ""
        TextBox5.Clear()
        ResetQuantity()
        dgvlistproducts.Rows.Clear()   ' top grid blank
        DataGridView1.Rows.Clear()     ' cart blank
        TextBox1.Text = "0.00"
    End Sub

End Class