Imports System.Globalization
Imports MySql.Data.MySqlClient

Public Class frmPOS

    Private foundStudentId As Integer = 0
    Private activeCategory As String = ""

    ' Column names of the top grid (dgvlistproducts) as generated by the designer
    Private Const COL_NAME As String = "DataGridViewTextBoxColumn1"
    Private Const COL_SIZE As String = "DataGridViewTextBoxColumn2"
    Private Const COL_PRICE As String = "DataGridViewTextBoxColumn3"
    Private Const COL_STOCK As String = "DataGridViewTextBoxColumn4"

    Private ReadOnly gradeLevels As String() = {"Kinder", "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6",
        "Grade 7", "Grade 8", "Grade 9", "Grade 10", "Grade 11", "Grade 12",
        "1st Year College", "2nd Year College", "3rd Year College", "4th Year College"}

    Private Sub frmPOS_Load(sender As Object, e As EventArgs) Handles MyBase.Load


        SetupGrid(dgvlistproducts)
        SetupGrid(dgvCart)
        dgvlistproducts.Columns(COL_PRICE).DefaultCellStyle.Format = "N2"
        dgvCart.Columns("UnitPrice").DefaultCellStyle.Format = "N2"
        dgvCart.Columns("SubTotal").DefaultCellStyle.Format = "N2"

        nudQuantity.DecimalPlaces = 0
        nudQuantity.Minimum = 0
        ResetQuantity()

        txtTotalAMount.Text = "0.00"
        ResetCustomerInfo()
    End Sub

    Private Sub SetupGrid(dgv As DataGridView)
        dgv.ReadOnly = True
        dgv.AllowUserToAddRows = False
        dgv.AllowUserToDeleteRows = False
        dgv.MultiSelect = False
        dgv.SelectionMode = DataGridViewSelectionMode.FullRowSelect
    End Sub

    Private Sub CategoryButton_Click(sender As Object, e As EventArgs)
        Dim btn As Button = DirectCast(sender, Button)

        ResetQuantity()
        LoadProducts()
    End Sub

    Private Sub txtProductSearch_TextChanged(sender As Object, e As EventArgs) Handles txtProductSearch.TextChanged
        ResetQuantity()
        LoadProducts()
    End Sub

    Private Sub picSearchProduct_Click(sender As Object, e As EventArgs) Handles picSearchProduct.Click
        LoadProducts()
    End Sub

    Private Sub LoadProducts()
        dgvlistproducts.Rows.Clear()

        Dim keyword As String = txtProductSearch.Text.Trim()
        If activeCategory = "" AndAlso keyword = "" Then Exit Sub   ' nothing chosen yet -> blank list

        Dim query As String =
            "SELECT v.variant_id, v.product_code, p.product_name, p.product_description, c.category_name, ct.type_name, " &
            "v.size, p.unit_price, v.quantity_on_hand, v.reorder_level " &
            "FROM TBL_PRODUCT_VARIANTS v " &
            "INNER JOIN TBL_PRODUCTS p ON v.product_id = p.product_id " &
            "INNER JOIN TBL_CATEGORY_TYPES ct ON p.category_type_id = ct.category_type_id " &
            "INNER JOIN TBL_CATEGORIES c ON ct.category_id = c.category_id " &
            "WHERE p.status = 'Active' AND (@cat = '' OR c.category_name = @cat) " &
            "AND (@kw = '' OR v.product_code LIKE @like OR p.product_name LIKE @like) " &
            "ORDER BY p.product_name, v.size"

        Dim dt As DataTable = GetDataTable(query,
            New String() {"@cat", "@kw", "@like"},
            New Object() {activeCategory, keyword, "%" & keyword & "%"})

        For Each r As DataRow In dt.Rows
            Dim stock As Integer = Convert.ToInt32(r("quantity_on_hand"))
            Dim reorder As Integer = Convert.ToInt32(r("reorder_level"))
            Dim status As String = If(stock <= 0, "Out of Stock", If(stock <= reorder, "Low Stock", "In Stock"))

            Dim idx As Integer = dgvlistproducts.Rows.Add(
                r("product_code").ToString(),
                r("product_name").ToString(),
                If(IsDBNull(r("product_description")), "", r("product_description").ToString()),
                r("category_name").ToString(),
                r("type_name").ToString(),
                r("size").ToString(),
                Convert.ToDecimal(r("unit_price")),
                stock,
                reorder,
                status)
            dgvlistproducts.Rows(idx).Tag = Convert.ToInt32(r("variant_id"))
        Next

        ClearGridSelection(dgvlistproducts)
    End Sub

    ' Clicking an item sets the quantity to 1 (user can raise it, never above stock)
    Private Sub dgvlistproducts_CellClick(sender As Object, e As DataGridViewCellEventArgs) Handles dgvlistproducts.CellClick
        If e.RowIndex < 0 Then Exit Sub

        Dim stock As Integer = Convert.ToInt32(dgvlistproducts.Rows(e.RowIndex).Cells(COL_STOCK).Value)
        If stock <= 0 Then
            ResetQuantity()
            MsgBox("This item is out of stock.", vbExclamation, "Point of Sale")
            Exit Sub
        End If

        nudQuantity.Maximum = stock
        nudQuantity.Value = 1
    End Sub

    ' ================= QUANTITY: NO NEGATIVES =================
    Private Sub nudQuantity_KeyPress(sender As Object, e As KeyPressEventArgs) Handles nudQuantity.KeyPress
        ' digits only: blocks "-", "." and letters
        If Not Char.IsDigit(e.KeyChar) AndAlso Not Char.IsControl(e.KeyChar) Then e.Handled = True
    End Sub

    Private Sub ResetQuantity()
        nudQuantity.Value = 0
        nudQuantity.Maximum = 0
    End Sub

    ' ================= ADD TO CART =================
    Private Sub btnAddToCart_Click(sender As Object, e As EventArgs) Handles btnAddToCart.Click
        If dgvlistproducts.SelectedRows.Count = 0 Then
            MsgBox("Please click an item in the list first.", vbExclamation, "Point of Sale")
            Exit Sub
        End If

        Dim qty As Integer = Convert.ToInt32(nudQuantity.Value)
        If qty <= 0 Then
            MsgBox("Quantity must be at least 1.", vbExclamation, "Point of Sale")
            Exit Sub
        End If

        Dim prow As DataGridViewRow = dgvlistproducts.SelectedRows(0)
        Dim variantId As Integer = Convert.ToInt32(prow.Tag)
        Dim stock As Integer = Convert.ToInt32(prow.Cells(COL_STOCK).Value)
        Dim price As Decimal = Convert.ToDecimal(prow.Cells(COL_PRICE).Value)

        ' Is this item already in the cart? Then add to its quantity
        Dim existing As DataGridViewRow = Nothing
        For Each crow As DataGridViewRow In dgvCart.Rows
            If Convert.ToInt32(crow.Tag) = variantId Then
                existing = crow
                Exit For
            End If
        Next

        Dim alreadyInCart As Integer = If(existing IsNot Nothing, Convert.ToInt32(existing.Cells("Quantity").Value), 0)
        If alreadyInCart + qty > stock Then
            MsgBox("Only " & stock & " item(s) in stock. You already have " & alreadyInCart & " in the cart.", vbExclamation, "Point of Sale")
            Exit Sub
        End If

        If existing IsNot Nothing Then
            Dim newQty As Integer = alreadyInCart + qty
            existing.Cells("Quantity").Value = newQty
            existing.Cells("SubTotal").Value = newQty * price
        Else
            Dim idx As Integer = dgvCart.Rows.Add(
                prow.Cells(COL_NAME).Value,
                prow.Cells(COL_SIZE).Value,
                qty,
                price,
                qty * price)
            dgvCart.Rows(idx).Tag = variantId
        End If

        ResetQuantity()
        ClearGridSelection(dgvlistproducts)
        ClearGridSelection(dgvCart)
        RecalculateTotal()
        InvalidatePayment()
    End Sub

    ' ================= REMOVE ITEM =================
    Private Sub btnRemoveItem_Click(sender As Object, e As EventArgs) Handles btnRemoveItem.Click
        If dgvCart.Rows.Count = 0 Then
            MsgBox("The cart is already empty.", vbInformation, "Point of Sale")
            Exit Sub
        End If

        If dgvCart.SelectedRows.Count > 0 Then
            ' an item was clicked -> remove that item only
            dgvCart.Rows.RemoveAt(dgvCart.SelectedRows(0).Index)
        Else
            ' nothing clicked -> remove everything
            If MsgBox("No item is selected. Remove ALL items from the cart?", vbYesNo + vbQuestion, "Point of Sale") <> MsgBoxResult.Yes Then Exit Sub
            dgvCart.Rows.Clear()
        End If

        ClearGridSelection(dgvCart)
        RecalculateTotal()
        InvalidatePayment()
    End Sub

    ' Clicking the empty grey area of the cart un-selects, so "Remove Item" removes all again
    Private Sub dgvCart_MouseDown(sender As Object, e As MouseEventArgs) Handles dgvCart.MouseDown
        If dgvCart.HitTest(e.X, e.Y).Type = DataGridViewHitTestType.None Then
            ClearGridSelection(dgvCart)
        End If
    End Sub

    ' ================= CLEAR (customer + payment method only) =================
    Private Sub btnClear_Click(sender As Object, e As EventArgs) Handles btnClear.Click
        ResetCustomerInfo()
    End Sub

    ' ================= CANCEL TRANSACTION =================
    Private Sub btnCancelTransaction_Click(sender As Object, e As EventArgs) Handles btnCancelTransaction.Click
        If MsgBox("Cancel this transaction? All entered details and both item lists will be cleared.", vbYesNo + vbQuestion, "Point of Sale") = MsgBoxResult.Yes Then
            ResetAll()
        End If
    End Sub

    ' ================= SETTLE PAYMENT (opens frmPayment) =================
    Private Sub btnSettlePayment_Click(sender As Object, e As EventArgs) Handles btnSettlePayment.Click
        If dgvCart.Rows.Count = 0 Then
            MsgBox("Add at least one item to the cart first.", vbExclamation, "Point of Sale")
            Exit Sub
        End If

        Dim grandTotal As Decimal = ToMoney(txtTotalAMount.Text)

        Using frm As New frmPayment()
            frm.GrandTotal = grandTotal
            If frm.ShowDialog(Me) = DialogResult.OK Then
                txtReferenceNo.Text = frm.ResultORNo
                txtAmountReceived.Text = frm.ResultReceived.ToString("N2")
                txtAmountChange.Text = frm.ResultChange.ToString("N2")
            End If
        End Using
    End Sub

    ' ================= SAVE TRANSACTION =================
    Private Sub btnSaveTransaction_Click(sender As Object, e As EventArgs) Handles btnSaveTransaction.Click
        If dgvCart.Rows.Count = 0 Then
            MsgBox("Add at least one item to the cart first.", vbExclamation, "Point of Sale")
            Exit Sub
        End If

        If String.IsNullOrWhiteSpace(txtReferenceNo.Text) Then
            MsgBox("Payment is not settled (or the payment method was cleared). Click 'Settle Payment' first.", vbExclamation, "Point of Sale")
            Exit Sub
        End If

        If String.IsNullOrWhiteSpace(txtStudentName.Text) Then
            MsgBox("Enter the buyer's name (or look up a Student No.).", vbExclamation, "Point of Sale")
            Exit Sub
        End If

        Dim total As Decimal = ToMoney(txtTotalAMount.Text)
        Dim received As Decimal = ToMoney(txtAmountReceived.Text)
        Dim change As Decimal = ToMoney(txtAmountChange.Text)
        If total <= 0 OrElse received < total OrElse change < 0 Then
            MsgBox("The payment does not cover the total. Click 'Settle Payment' again.", vbExclamation, "Point of Sale")
            Exit Sub
        End If

        Dim buyerType As String = If(foundStudentId > 0, "Student", "Walk-in")
        Dim saved As Boolean = False
        Dim txnNo As String = NewTransactionNo()

        Try
            If Not connection() Then Exit Sub
            Dim trans As MySqlTransaction = cn.BeginTransaction()
            Try
                Dim transactionId As Long = 0
                Dim insTxn As String = "INSERT INTO TBL_TRANSACTIONS " &
                    "(transaction_no, buyer_type, student_id, buyer_name, or_no, or_date, payment_method, total_amount, amount_paid, amount_change, created_by, status) " &
                    "VALUES (@tno, @bt, @sid, @bn, @orno, @ord, @pm, @tot, @paid, @chg, @by, 'Completed')"

                Using c1 As New MySqlCommand(insTxn, cn, trans)
                    c1.Parameters.AddWithValue("@tno", txnNo)
                    c1.Parameters.AddWithValue("@bt", buyerType)
                    c1.Parameters.AddWithValue("@sid", If(foundStudentId > 0, CType(foundStudentId, Object), DBNull.Value))
                    c1.Parameters.AddWithValue("@bn", txtStudentName.Text.Trim())
                    c1.Parameters.AddWithValue("@orno", txtReferenceNo.Text.Trim())
                    c1.Parameters.AddWithValue("@tot", total)
                    c1.Parameters.AddWithValue("@paid", received)
                    c1.Parameters.AddWithValue("@chg", change)
                    c1.Parameters.AddWithValue("@by", currentuser.UserID)
                    c1.ExecuteNonQuery()
                    transactionId = c1.LastInsertedId
                End Using

                For Each row As DataGridViewRow In dgvCart.Rows
                    Dim variantId As Integer = Convert.ToInt32(row.Tag)
                    Dim subtotal As Decimal = Convert.ToDecimal(row.Cells("SubTotal").Value)
                    Dim qty As Integer = Convert.ToInt32(row.Cells("Quantity").Value)

                    Using c2 As New MySqlCommand("INSERT INTO TBL_TRANSACTION_ITEMS (transaction_id, variant_id, quantity, subtotal) VALUES (@t, @v, @q, @s)", cn, trans)
                        c2.Parameters.AddWithValue("@t", transactionId)
                        c2.Parameters.AddWithValue("@v", variantId)
                        c2.Parameters.AddWithValue("@q", qty)
                        c2.Parameters.AddWithValue("@s", subtotal)
                        c2.ExecuteNonQuery()
                    End Using

                    Using c3 As New MySqlCommand("UPDATE TBL_PRODUCT_VARIANTS SET quantity_on_hand = quantity_on_hand - @q WHERE variant_id = @v AND quantity_on_hand >= @q", cn, trans)
                        c3.Parameters.AddWithValue("@q", qty)
                        c3.Parameters.AddWithValue("@v", variantId)
                        If c3.ExecuteNonQuery() = 0 Then
                            Throw New Exception("Not enough stock left for " & row.Cells("ProductName").Value.ToString() & ".")
                        End If
                    End Using
                Next

                trans.Commit()
                saved = True
            Catch exInner As Exception
                trans.Rollback()
                MsgBox("Transaction failed and was rolled back: " & exInner.Message, vbCritical, "Point of Sale")
            End Try
            cn.Close()
        Catch ex As Exception
            If cn.State = ConnectionState.Open Then cn.Close()
            MsgBox("Database error: " & ex.Message, vbCritical, "Error")
        End Try

        If saved Then
            LogActivity("Sale", txnNo, "Sale to " & txtStudentName.Text.Trim() & " - Total: " & total.ToString("N2") & " (" & ", OR " & txtReferenceNo.Text.Trim() & ")")
            MsgBox("Transaction saved successfully. You can view it in Transaction History.", vbInformation, "Point of Sale")
            ResetAll()
        End If
    End Sub

    ' ================= HELPERS =================
    Private Sub RecalculateTotal()
        Dim total As Decimal = 0
        For Each row As DataGridViewRow In dgvCart.Rows
            total += ToMoney(Convert.ToString(row.Cells("SubTotal").Value))
        Next
        txtTotalAMount.Text = total.ToString("N2")
    End Sub

    Private Function ToMoney(s As String) As Decimal
        Dim v As Decimal
        If Decimal.TryParse(s, NumberStyles.Number, CultureInfo.CurrentCulture, v) Then Return v
        Return 0
    End Function

    Private Sub ClearGridSelection(dgv As DataGridView)
        dgv.ClearSelection()
        dgv.CurrentCell = Nothing
    End Sub

    ' If the cart changes after payment was settled, the old payment no longer matches the total
    Private Sub InvalidatePayment()
        If String.IsNullOrWhiteSpace(txtReferenceNo.Text) Then Exit Sub
        ResetPaymentInfo()
        MsgBox("The cart was changed, so the payment was cleared. Click 'Settle Payment' again.", vbInformation, "Point of Sale")
    End Sub

    Private Sub ResetCustomerInfo()

        txtStudentName.Clear()
        txtStudentName.ReadOnly = False
        txtProgramStrand.Clear()
        foundStudentId = 0
    End Sub

    Private Sub ResetPaymentInfo()
        txtReferenceNo.Clear()
        txtAmountReceived.Clear()
        txtAmountChange.Clear()

    End Sub

    Private Sub ResetAll()
        ResetCustomerInfo()
        ResetPaymentInfo()
        activeCategory = ""
        txtProductSearch.Clear()
        ResetQuantity()
        dgvlistproducts.Rows.Clear()
        dgvCart.Rows.Clear()
        txtTotalAMount.Text = "0.00"
    End Sub

End Class